//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ps_discharger {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtPrj_No;
		protected global::System.Web.UI.WebControls.TextBox txtPrj_Name;
	protected global::System.Web.UI.WebControls.Label lblExp_No;
		protected global::System.Web.UI.WebControls.TextBox txtCode;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtCodeID;
		protected global::System.Web.UI.WebControls.TextBox txtRepresentative;
		protected global::System.Web.UI.WebControls.TextBox txtTel;
		protected global::System.Web.UI.WebControls.TextBox txtManager;
		protected global::System.Web.UI.WebControls.TextBox txtLicence_ID;
		protected global::System.Web.UI.WebControls.TextBox txtLicence_Issue_Date;
		protected global::System.Web.UI.WebControls.TextBox txtSort;
		protected global::System.Web.UI.WebControls.TextBox txtConn_ManholeID;
		protected global::System.Web.UI.WebControls.TextBox txtBusiness;
		protected global::System.Web.UI.WebControls.TextBox txtProcess;
		protected global::System.Web.UI.WebControls.TextBox txtPollutant_Name;
		protected global::System.Web.UI.WebControls.TextBox txtTreatment_Method;
		protected global::System.Web.UI.WebControls.TextBox txtTreatment_Facilities;
		protected global::System.Web.UI.WebControls.TextBox txtTreatment_Capacity;
		protected global::System.Web.UI.WebControls.TextBox txtWater_Daily_Consumption;
		protected global::System.Web.UI.WebControls.TextBox txtWater_Self_Supply_Daily;
		protected global::System.Web.UI.WebControls.TextBox txtWater_Discharge_Quantity;
		protected global::System.Web.UI.WebControls.TextBox txtProduction_Waste_Quantity;
		protected global::System.Web.UI.WebControls.TextBox txtSanitary_Waste_Quantity;
		protected global::System.Web.UI.WebControls.TextBox txtTemp;
		protected global::System.Web.UI.WebControls.TextBox txtpH;
		protected global::System.Web.UI.WebControls.TextBox txtSS;
		protected global::System.Web.UI.WebControls.TextBox txtBOD5;
		protected global::System.Web.UI.WebControls.TextBox txtCODcr;
		protected global::System.Web.UI.WebControls.TextBox txtNH3_N;
		protected global::System.Web.UI.WebControls.TextBox txtTN;
		protected global::System.Web.UI.WebControls.TextBox txtTP;
		protected global::System.Web.UI.WebControls.TextBox txtSunit;
		protected global::System.Web.UI.WebControls.TextBox txtSdate;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtNote;
		protected global::System.Web.UI.WebControls.TextBox txtExp_NoOri;
		protected global::System.Web.UI.WebControls.TextBox txtfilename;
		protected global::System.Web.UI.WebControls.TextBox txtupdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
