//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ps_discharger {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPrj_No;
	protected global::System.Web.UI.WebControls.Label lblPrj_Name;
	protected global::System.Web.UI.WebControls.Label lblExp_No;
	protected global::System.Web.UI.WebControls.Label lblCode;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblCodeID;
	protected global::System.Web.UI.WebControls.Label lblRepresentative;
	protected global::System.Web.UI.WebControls.Label lblTel;
	protected global::System.Web.UI.WebControls.Label lblManager;
	protected global::System.Web.UI.WebControls.Label lblLicence_ID;
	protected global::System.Web.UI.WebControls.Label lblLicence_Issue_Date;
	protected global::System.Web.UI.WebControls.Label lblSort;
	protected global::System.Web.UI.WebControls.Label lblConn_ManholeID;
	protected global::System.Web.UI.WebControls.Label lblBusiness;
	protected global::System.Web.UI.WebControls.Label lblProcess;
	protected global::System.Web.UI.WebControls.Label lblPollutant_Name;
	protected global::System.Web.UI.WebControls.Label lblTreatment_Method;
	protected global::System.Web.UI.WebControls.Label lblTreatment_Facilities;
	protected global::System.Web.UI.WebControls.Label lblTreatment_Capacity;
	protected global::System.Web.UI.WebControls.Label lblWater_Daily_Consumption;
	protected global::System.Web.UI.WebControls.Label lblWater_Self_Supply_Daily;
	protected global::System.Web.UI.WebControls.Label lblWater_Discharge_Quantity;
	protected global::System.Web.UI.WebControls.Label lblProduction_Waste_Quantity;
	protected global::System.Web.UI.WebControls.Label lblSanitary_Waste_Quantity;
	protected global::System.Web.UI.WebControls.Label lblTemp;
	protected global::System.Web.UI.WebControls.Label lblpH;
	protected global::System.Web.UI.WebControls.Label lblSS;
	protected global::System.Web.UI.WebControls.Label lblBOD5;
	protected global::System.Web.UI.WebControls.Label lblCODcr;
	protected global::System.Web.UI.WebControls.Label lblNH3_N;
	protected global::System.Web.UI.WebControls.Label lblTN;
	protected global::System.Web.UI.WebControls.Label lblTP;
	protected global::System.Web.UI.WebControls.Label lblSunit;
	protected global::System.Web.UI.WebControls.Label lblSdate;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblNote;
	protected global::System.Web.UI.WebControls.Label lblExp_NoOri;
	protected global::System.Web.UI.WebControls.Label lblfilename;
	protected global::System.Web.UI.WebControls.Label lblupdate;


       
    }
}
