//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ps_valve {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPrj_No;
	protected global::System.Web.UI.WebControls.Label lblPrj_Name;
	protected global::System.Web.UI.WebControls.Label lblExp_No;
	protected global::System.Web.UI.WebControls.Label lblMapCode;
	protected global::System.Web.UI.WebControls.Label lblSewageSystem_ID;
	protected global::System.Web.UI.WebControls.Label lblStormSystem_ID;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblX;
	protected global::System.Web.UI.WebControls.Label lblY;
	protected global::System.Web.UI.WebControls.Label lblHigh;
	protected global::System.Web.UI.WebControls.Label lblValve_Type;
	protected global::System.Web.UI.WebControls.Label lblManufacturer;
	protected global::System.Web.UI.WebControls.Label lblValveModel;
	protected global::System.Web.UI.WebControls.Label lblCode;
	protected global::System.Web.UI.WebControls.Label lblModel;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPointPosition;
	protected global::System.Web.UI.WebControls.Label lblDataSource;
	protected global::System.Web.UI.WebControls.Label lblVisibility;
	protected global::System.Web.UI.WebControls.Label lblSunit;
	protected global::System.Web.UI.WebControls.Label lblSdate;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblMdate;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblDataListID;
	protected global::System.Web.UI.WebControls.Label lblEname;
	protected global::System.Web.UI.WebControls.Label lblDesign_Dept;
	protected global::System.Web.UI.WebControls.Label lblConster_Dept;
	protected global::System.Web.UI.WebControls.Label lblBelong;
	protected global::System.Web.UI.WebControls.Label lblOperator;
	protected global::System.Web.UI.WebControls.Label lblNote;
	protected global::System.Web.UI.WebControls.Label lblExp_NoOri;
	protected global::System.Web.UI.WebControls.Label lblfilename;
	protected global::System.Web.UI.WebControls.Label lblupdate;


       
    }
}
