//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.pipeobjectencode {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblnumber;
	protected global::System.Web.UI.WebControls.Label lblobjcate;
	protected global::System.Web.UI.WebControls.Label lblcode;
	protected global::System.Web.UI.WebControls.Label lblobjname;
	protected global::System.Web.UI.WebControls.Label lblnote;
	protected global::System.Web.UI.WebControls.Label lbltablename;
	protected global::System.Web.UI.WebControls.Label lblobjtype;


       
    }
}
