//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cjplp {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMapCode;
		protected global::System.Web.UI.WebControls.TextBox txtStormSystem_ID;
		protected global::System.Web.UI.WebControls.TextBox txtExp_No;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtX;
		protected global::System.Web.UI.WebControls.TextBox txtY;
		protected global::System.Web.UI.WebControls.TextBox txtHigh;
		protected global::System.Web.UI.WebControls.TextBox txtWellDeep;
		protected global::System.Web.UI.WebControls.TextBox txtOffset;
		protected global::System.Web.UI.WebControls.TextBox txtFeature;
		protected global::System.Web.UI.WebControls.TextBox txtSubsid;
		protected global::System.Web.UI.WebControls.TextBox txtModel;
		protected global::System.Web.UI.WebControls.TextBox txtWellPipes;
		protected global::System.Web.UI.WebControls.TextBox txtWellShape;
		protected global::System.Web.UI.WebControls.TextBox txtWellSize;
		protected global::System.Web.UI.WebControls.TextBox txtWellMaterial;
		protected global::System.Web.UI.WebControls.TextBox txtWaterDeep;
		protected global::System.Web.UI.WebControls.TextBox txtMudDeep;
		protected global::System.Web.UI.WebControls.TextBox txtInlet_Type;
		protected global::System.Web.UI.WebControls.TextBox txtOutfallType;
		protected global::System.Web.UI.WebControls.TextBox txtReceiveWater;
		protected global::System.Web.UI.WebControls.TextBox txtFlap;
		protected global::System.Web.UI.WebControls.TextBox txtFlap_Diameter;
		protected global::System.Web.UI.WebControls.TextBox txtFlap_TopEle;
		protected global::System.Web.UI.WebControls.TextBox txtFlap_BotEle;
		protected global::System.Web.UI.WebControls.TextBox txtFlap_Material;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtPointPosition;
		protected global::System.Web.UI.WebControls.TextBox txtDataSource;
		protected global::System.Web.UI.WebControls.TextBox txtVisibility;
		protected global::System.Web.UI.WebControls.TextBox txtSdate;
		protected global::System.Web.UI.WebControls.TextBox txtMdate;
		protected global::System.Web.UI.WebControls.TextBox txtManhole_Type;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtNote;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
