//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cjplp {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMapCode;
	protected global::System.Web.UI.WebControls.Label lblStormSystem_ID;
	protected global::System.Web.UI.WebControls.Label lblExp_No;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblX;
	protected global::System.Web.UI.WebControls.Label lblY;
	protected global::System.Web.UI.WebControls.Label lblHigh;
	protected global::System.Web.UI.WebControls.Label lblWellDeep;
	protected global::System.Web.UI.WebControls.Label lblOffset;
	protected global::System.Web.UI.WebControls.Label lblFeature;
	protected global::System.Web.UI.WebControls.Label lblSubsid;
	protected global::System.Web.UI.WebControls.Label lblModel;
	protected global::System.Web.UI.WebControls.Label lblWellPipes;
	protected global::System.Web.UI.WebControls.Label lblWellShape;
	protected global::System.Web.UI.WebControls.Label lblWellSize;
	protected global::System.Web.UI.WebControls.Label lblWellMaterial;
	protected global::System.Web.UI.WebControls.Label lblWaterDeep;
	protected global::System.Web.UI.WebControls.Label lblMudDeep;
	protected global::System.Web.UI.WebControls.Label lblInlet_Type;
	protected global::System.Web.UI.WebControls.Label lblOutfallType;
	protected global::System.Web.UI.WebControls.Label lblReceiveWater;
	protected global::System.Web.UI.WebControls.Label lblFlap;
	protected global::System.Web.UI.WebControls.Label lblFlap_Diameter;
	protected global::System.Web.UI.WebControls.Label lblFlap_TopEle;
	protected global::System.Web.UI.WebControls.Label lblFlap_BotEle;
	protected global::System.Web.UI.WebControls.Label lblFlap_Material;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPointPosition;
	protected global::System.Web.UI.WebControls.Label lblDataSource;
	protected global::System.Web.UI.WebControls.Label lblVisibility;
	protected global::System.Web.UI.WebControls.Label lblSdate;
	protected global::System.Web.UI.WebControls.Label lblMdate;
	protected global::System.Web.UI.WebControls.Label lblManhole_Type;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lblNote;


       
    }
}
