//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ps_pumpstation {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPrj_No;
		protected global::System.Web.UI.WebControls.TextBox txtPrj_Name;
		protected global::System.Web.UI.WebControls.TextBox txtExp_No;
		protected global::System.Web.UI.WebControls.TextBox txtMapCode;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtArea;
		protected global::System.Web.UI.WebControls.TextBox txtService_Dis;
		protected global::System.Web.UI.WebControls.TextBox txtService_Area;
		protected global::System.Web.UI.WebControls.TextBox txtSewageSystem_ID;
		protected global::System.Web.UI.WebControls.TextBox txtStormSystem_ID;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtX;
		protected global::System.Web.UI.WebControls.TextBox txtY;
		protected global::System.Web.UI.WebControls.TextBox txtHigh;
		protected global::System.Web.UI.WebControls.TextBox txtPS_Category2;
		protected global::System.Web.UI.WebControls.TextBox txtPs_Num;
		protected global::System.Web.UI.WebControls.TextBox txtDesign_Storm;
		protected global::System.Web.UI.WebControls.TextBox txtDesign_Sewer;
		protected global::System.Web.UI.WebControls.TextBox txtCur_Strom;
		protected global::System.Web.UI.WebControls.TextBox txtCur_Sew;
		protected global::System.Web.UI.WebControls.TextBox txtMin_Level;
		protected global::System.Web.UI.WebControls.TextBox txtControl_Level;
		protected global::System.Web.UI.WebControls.TextBox txtWarnning_Level;
		protected global::System.Web.UI.WebControls.TextBox txtS_Invert;
		protected global::System.Web.UI.WebControls.TextBox txtPSize;
		protected global::System.Web.UI.WebControls.TextBox txtOverOutfallID;
		protected global::System.Web.UI.WebControls.TextBox txtTel;
		protected global::System.Web.UI.WebControls.TextBox txtForebayLen;
		protected global::System.Web.UI.WebControls.TextBox txtForebayWid;
		protected global::System.Web.UI.WebControls.TextBox txtForebayDep;
		protected global::System.Web.UI.WebControls.TextBox txtCode;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtDataSource;
		protected global::System.Web.UI.WebControls.TextBox txtSunit;
		protected global::System.Web.UI.WebControls.TextBox txtSdate;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtMdate;
		protected global::System.Web.UI.WebControls.TextBox txtDataListID;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtEname;
		protected global::System.Web.UI.WebControls.TextBox txtDesign_Dept;
		protected global::System.Web.UI.WebControls.TextBox txtConster_Dept;
		protected global::System.Web.UI.WebControls.TextBox txtBelong;
		protected global::System.Web.UI.WebControls.TextBox txtOperator;
		protected global::System.Web.UI.WebControls.TextBox txtNote;
		protected global::System.Web.UI.WebControls.TextBox txtExp_NoOri;
		protected global::System.Web.UI.WebControls.TextBox txtfilename;
		protected global::System.Web.UI.WebControls.TextBox txtupdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
