//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cjpll {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtStormSystem_ID;
		protected global::System.Web.UI.WebControls.TextBox txtS_Point;
		protected global::System.Web.UI.WebControls.TextBox txtS_Deep;
		protected global::System.Web.UI.WebControls.TextBox txtS_Elev;
		protected global::System.Web.UI.WebControls.TextBox txtE_Point;
		protected global::System.Web.UI.WebControls.TextBox txtE_Deep;
		protected global::System.Web.UI.WebControls.TextBox txtE_Elev;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtPressure_Type;
		protected global::System.Web.UI.WebControls.TextBox txtInvert_Silphon;
		protected global::System.Web.UI.WebControls.TextBox txtMaterial;
		protected global::System.Web.UI.WebControls.TextBox txtShapeType;
		protected global::System.Web.UI.WebControls.TextBox txtGrade;
		protected global::System.Web.UI.WebControls.TextBox txtPsize;
		protected global::System.Web.UI.WebControls.TextBox txtFlowDir;
		protected global::System.Web.UI.WebControls.TextBox txtConduitStyle;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtDataSource;
		protected global::System.Web.UI.WebControls.TextBox txtSdate;
		protected global::System.Web.UI.WebControls.TextBox txtMdate;
		protected global::System.Web.UI.WebControls.TextBox txtPipe_Type;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtNote;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
