//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.cjpll {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblStormSystem_ID;
	protected global::System.Web.UI.WebControls.Label lblS_Point;
	protected global::System.Web.UI.WebControls.Label lblS_Deep;
	protected global::System.Web.UI.WebControls.Label lblS_Elev;
	protected global::System.Web.UI.WebControls.Label lblE_Point;
	protected global::System.Web.UI.WebControls.Label lblE_Deep;
	protected global::System.Web.UI.WebControls.Label lblE_Elev;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblPressure_Type;
	protected global::System.Web.UI.WebControls.Label lblInvert_Silphon;
	protected global::System.Web.UI.WebControls.Label lblMaterial;
	protected global::System.Web.UI.WebControls.Label lblShapeType;
	protected global::System.Web.UI.WebControls.Label lblGrade;
	protected global::System.Web.UI.WebControls.Label lblPsize;
	protected global::System.Web.UI.WebControls.Label lblFlowDir;
	protected global::System.Web.UI.WebControls.Label lblConduitStyle;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblDataSource;
	protected global::System.Web.UI.WebControls.Label lblSdate;
	protected global::System.Web.UI.WebControls.Label lblMdate;
	protected global::System.Web.UI.WebControls.Label lblPipe_Type;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblNote;


       
    }
}
