//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ps_pipe {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtPrj_No;
		protected global::System.Web.UI.WebControls.TextBox txtPrj_Name;
	protected global::System.Web.UI.WebControls.Label lblLno;
		protected global::System.Web.UI.WebControls.TextBox txtGrade;
		protected global::System.Web.UI.WebControls.TextBox txtS_Point;
		protected global::System.Web.UI.WebControls.TextBox txtS_Deep;
		protected global::System.Web.UI.WebControls.TextBox txtIn_Elev;
		protected global::System.Web.UI.WebControls.TextBox txtE_Point;
		protected global::System.Web.UI.WebControls.TextBox txtE_Deep;
		protected global::System.Web.UI.WebControls.TextBox txtOut_Elev;
		protected global::System.Web.UI.WebControls.TextBox txtSewageSystem_ID;
		protected global::System.Web.UI.WebControls.TextBox txtStormSystem_ID;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtCode;
		protected global::System.Web.UI.WebControls.TextBox txtPressure_Type;
		protected global::System.Web.UI.WebControls.TextBox txtInvert_Silphon;
		protected global::System.Web.UI.WebControls.TextBox txtMaterial;
		protected global::System.Web.UI.WebControls.TextBox txtServiceLife;
		protected global::System.Web.UI.WebControls.TextBox txtShapeType;
		protected global::System.Web.UI.WebControls.TextBox txtPSize;
		protected global::System.Web.UI.WebControls.TextBox txtPipeLength;
		protected global::System.Web.UI.WebControls.TextBox txtFlowDir;
		protected global::System.Web.UI.WebControls.TextBox txtEmBed;
		protected global::System.Web.UI.WebControls.TextBox txtInterface;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtDataSource;
		protected global::System.Web.UI.WebControls.TextBox txtSunit;
		protected global::System.Web.UI.WebControls.TextBox txtSdate;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtMdate;
		protected global::System.Web.UI.WebControls.TextBox txtPlan;
		protected global::System.Web.UI.WebControls.TextBox txtPipe_Type;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtEname;
		protected global::System.Web.UI.WebControls.TextBox txtDesign_Dept;
		protected global::System.Web.UI.WebControls.TextBox txtConster_Dept;
		protected global::System.Web.UI.WebControls.TextBox txtBelong;
		protected global::System.Web.UI.WebControls.TextBox txtOperator;
		protected global::System.Web.UI.WebControls.TextBox txtNote;
		protected global::System.Web.UI.WebControls.TextBox txtExp_No0;
		protected global::System.Web.UI.WebControls.TextBox txtExp_No1;
		protected global::System.Web.UI.WebControls.TextBox txtfilename;
		protected global::System.Web.UI.WebControls.TextBox txtupdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
