//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ps_pipe {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPrj_No;
	protected global::System.Web.UI.WebControls.Label lblPrj_Name;
	protected global::System.Web.UI.WebControls.Label lblLno;
	protected global::System.Web.UI.WebControls.Label lblGrade;
	protected global::System.Web.UI.WebControls.Label lblS_Point;
	protected global::System.Web.UI.WebControls.Label lblS_Deep;
	protected global::System.Web.UI.WebControls.Label lblIn_Elev;
	protected global::System.Web.UI.WebControls.Label lblE_Point;
	protected global::System.Web.UI.WebControls.Label lblE_Deep;
	protected global::System.Web.UI.WebControls.Label lblOut_Elev;
	protected global::System.Web.UI.WebControls.Label lblSewageSystem_ID;
	protected global::System.Web.UI.WebControls.Label lblStormSystem_ID;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblCode;
	protected global::System.Web.UI.WebControls.Label lblPressure_Type;
	protected global::System.Web.UI.WebControls.Label lblInvert_Silphon;
	protected global::System.Web.UI.WebControls.Label lblMaterial;
	protected global::System.Web.UI.WebControls.Label lblServiceLife;
	protected global::System.Web.UI.WebControls.Label lblShapeType;
	protected global::System.Web.UI.WebControls.Label lblPSize;
	protected global::System.Web.UI.WebControls.Label lblPipeLength;
	protected global::System.Web.UI.WebControls.Label lblFlowDir;
	protected global::System.Web.UI.WebControls.Label lblEmBed;
	protected global::System.Web.UI.WebControls.Label lblInterface;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblDataSource;
	protected global::System.Web.UI.WebControls.Label lblSunit;
	protected global::System.Web.UI.WebControls.Label lblSdate;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblMdate;
	protected global::System.Web.UI.WebControls.Label lblPlan;
	protected global::System.Web.UI.WebControls.Label lblPipe_Type;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblEname;
	protected global::System.Web.UI.WebControls.Label lblDesign_Dept;
	protected global::System.Web.UI.WebControls.Label lblConster_Dept;
	protected global::System.Web.UI.WebControls.Label lblBelong;
	protected global::System.Web.UI.WebControls.Label lblOperator;
	protected global::System.Web.UI.WebControls.Label lblNote;
	protected global::System.Web.UI.WebControls.Label lblExp_No0;
	protected global::System.Web.UI.WebControls.Label lblExp_No1;
	protected global::System.Web.UI.WebControls.Label lblfilename;
	protected global::System.Web.UI.WebControls.Label lblupdate;


       
    }
}
